#cloud-config
users:
  - name: ubuntu
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDbI7B6XaZo4MP9/Wg9XpQcfb/joiQsclhMuDFyR5cu5t7+CG2/qW6KYg89mn4FGJzEH+Wd5VIn2xh+9m7t+odckZB2K8GvTxoXDOQLGVn2T8T6IB4XzPfq5FZ8gSHXCe0R3jh9kV7WSZBW8WP7gAYX5w4m120K7SvT9/z0dL/+eucnn/WklZoV8tqfNP+s9yeyWmd7JY3oeQy53GfPOg+rc78/eyCH/5hCI4kbiYLHy0zMn+zyjLd6kFhTm7EyNHblJaPjdwSfCX//waedzIiABB6stByOpYaQ5GiP91hrnCdbCMhMd0EoJ9WE8vSdrH9tc5F84TFck4jhhbmVS6NRrbSdARQSTH/3ZfbHE5g9jdYIwkSA1K3H4ncDd/cjM5mGHYQBbM+f5uX98wW2bS+h9tDld+GE9btka7E4cNPkwDtsinmceqJIjhJuCsihrlLZzLHfyuxQtE9PF+4ZXMjw112nBqrsSviblJ3gLapUUg2YHeMSNEiABWEbhYh9q5U= force@force-GL65-9SEK
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
    lock_passwd: false
    passwd: $6$Jf1PFzaroD4ZRKHH$uQv4vSA22RoSjGrXVKbxwpRURqCx.PLqUDSdtqm8eaRPfzh/udhgC1L/H6CSWaNmsqNOrWhLsWBX5/ImnujbQ0
chpasswd:
  list: |
    ubuntu:Force4462
  expire: False
runcmd:
  - apt-get update
  - apt-get install -y unattended-upgrades
  - dpkg-reconfigure -plow unattended-upgrades
  - ufw allow OpenSSH
  - ufw allow 80/tcp
  - ufw allow 443/tcp
  - ufw allow 1194/udp
  - ufw enable
  - apt-get install -y openvpn easy-rsa
  - make-cadir /etc/openvpn/easy-rsa
  - cd /etc/openvpn/easy-rsa
  - ./easyrsa init-pki
  - ./easyrsa build-ca nopass
  - ./easyrsa gen-dh
  - ./easyrsa build-server-full server nopass
  - ./easyrsa build-client-full client1 nopass
  - openvpn --genkey --secret ta.key
  - cp pki/ca.crt pki/private/ca.key pki/issued/server.crt pki/private/server.key pki/dh.pem ta.key /etc/openvpn
  - ls -l /etc/openvpn/easy-rsa/pki
  - ls -l /etc/openvpn
  - echo 'port 1194' > /etc/openvpn/server.conf
  - echo 'proto udp' >> /etc/openvpn/server.conf
  - echo 'dev tun' >> /etc/openvpn/server.conf
  - echo 'ca ca.crt' >> /etc/openvpn/server.conf
  - echo 'cert server.crt' >> /etc/openvpn/server.conf
  - echo 'key server.key' >> /etc/openvpn/server.conf
  - echo 'dh dh.pem' >> /etc/openvpn/server.conf
  - echo 'tls-auth ta.key 0' >> /etc/openvpn/server.conf
  - echo 'cipher AES-256-CBC' >> /etc/openvpn/server.conf
  - echo 'user nobody' >> /etc/openvpn/server.conf
  - echo 'group nogroup' >> /etc/openvpn/server.conf
  - echo 'persist-key' >> /etc/openvpn/server.conf
  - echo 'persist-tun' >> /etc/openvpn/server.conf
  - echo 'status openvpn-status.log' >> /etc/openvpn/server.conf
  - echo 'log-append /var/log/openvpn.log' >> /etc/openvpn/server.conf
  - echo 'verb 3' >> /etc/openvpn/server.conf
  - echo 'push "redirect-gateway def1 bypass-dhcp"' >> /etc/openvpn/server.conf
  - echo 'push "dhcp-option DNS 8.8.8.8"' >> /etc/openvpn/server.conf
  - echo 'push "dhcp-option DNS 8.8.4.4"' >> /etc/openvpn/server.conf
  - echo 'tls-server' >> /etc/openvpn/server.conf
  - systemctl start openvpn@server
  - systemctl enable openvpn@server